# 1. Create a null vector of size 10

# 2. How to find the memory size of an array

# 3. Create a null vector of size 10 but the fifth value which is 1

# 4. Create a vector with values ranging from 15 to 45

# 5. Reverse a vector (The first element becomes last)

# 6. Write a NumPy program to add, subtract, multiply, divide arguments element-wise

# 7.
Write a NumPy program to round elements of the array to the nearest integer

# 8. Write a
NumPy program to get the floor and ceiling values of the elements of a NumPy array

# 9. Write a NumPy program to calculate mean across dimensions, in a 2D NumPy array.

# 10.
Write a NumPy program to convert angles from degrees to radians for all elements in a
given array.

# 11. What is the use of all and any function in numpy?

# 12. Create a 3x3 matrix with values ranging from 0 to 8
[[0 1 2]
[3 4 5]
[6 7 8]]

# 13. How to reverse the columns of a 2D array?
([[2, 1, 0],
[5, 4, 3],
[8, 7, 6]])

# 14. How to reverse the rows of a 2D array?
[[6, 7, 8],
[3, 4, 5],
[0, 1, 2]]

# 15. Find indices of non-zero elements from [1,2,0,0,4,0]

# 16. Write a NumPy program to compute the determinant of an array.

# 17. Write a NumPy program to compute the inverse of a given matrix

# 18. Create a random vector of size 30 and find the mean value

# 19. How to extract all numbers between a given range from a NumPy array?

# 20. Create a 3x3x3 array with random values

# 21. Create a 10x10 array with random values and find the minimum and maximum values

# 22. Create a 2d array with 1 on the border and 0 inside[[

# 1.

# 1.

# 1.

# 1.

# 1.

# 1.

# 1.

# 1.

# 1.

# 1.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 1.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 1.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 1.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 1.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 1.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 1.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 1.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 0.

# 1.

# 1.

# 1.

# 1.

# 1.

# 1.

# 1.

# 1.

# 1.

# 23. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

# 24. Create a 3x3 identity matrix

# 25. Create a 8x8 matrix and fill it with a checkerboard pattern
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

# 26. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

# 27. Given a 1D
array, negate all elements which are between 3 and 8, in place

# 28. How to round
away from zero a float array?

# 29. How to find common values between the two arrays?

# 30. Create a vector of size 10 with values ranging from 0 to 1, both excluded

# 31. Create a random vector of size 10 and sort it

# 32. Create a 5x5 matrix with row values ranging from 0 to 4
[[

# 0.

# 1.

# 2.

# 3.

# 0.

# 1.

# 2.

# 3.

# 0.

# 1.

# 2.

# 3.

# 0.

# 1.

# 2.

# 3.

# 0.

# 1.

# 2.

# 3.

# 33. Consider two random arrays A and B, check if they are equal

# 34. Create a random vector of size 10 and replace the maximum value by 0

# 35. How to find out multiple indices of an item?

# 36. What is the equivalent of enumerate for NumPy arrays?

# 37. How to sort an array by the nth column?

# 38. How to swap two rows of an array?

# 39. How to compute the mean of a NumPy array?

# 40. How to compute the median of a NumPy array?

# 41. How to compute the standard deviation of a NumPy array?

# 42. How to compute the mode of a NumPy array?

# 43. How to print only 3 decimal places in a python NumPy array?

# 44. Write a NumPy
program to compute the inverse of a given matrix

# 45. Write a NumPy program to
compute the covariance matrix of two given arrays

# 46. How to find the most frequent
value in a NumPy array?

# 47. How to convert 1D array to 3D array?

# 48. How to convert 4D array to 2D array?

# 49. Create a Numpy array filled with all zeros

# 50. Find the number of rows and columns of a given matrix using NumPy